services:
  # portfolio:
  #   build:
  #     context: ./rp-portfolio
  #     dockerfile: Dockerfile
  #   container_name: portfolio
  #   ports:
  #     - 8000:8000
  #   networks:
  #     - devopsnet
  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    image: jenkins
    container_name: jenkins
    restart: always
    volumes:
      - jenkins-data:/var/jenkins_home
    ports:
      - 8080:8080
    networks:
      - devopsnet

networks:
  devopsnet:
    driver: bridge

volumes:
  jenkins-data:
